### ISSUE TITLE
秘密情報をうまいこと提供する

### ISSUE THREAD

**Issue by kannna5296** [kannna5296/spring-batch-sample-infra#1]

**Comment by kannna5296** [comment]
AzurePipeline上で'az login'に近しいことをしないと処理ができない。
通常の'az login'だとブラウザ操作が必要なので、コマンドOnlyで処理したい。

DevOps上でサービスプリンシパルログインをしたいが、うまくいかない。
参考https://tech.nsw-cloud.jp/2018/12/28/%E3%82%B3%E3%83%9E%E3%83%B3%E3%83%89%E4%B8%80%E7%99%BA%E3%81%A7azure-cli%E3%81%AB%E3%82%B5%E3%82%A4%E3%83%B3%E3%82%A4%E3%83%B3/

**Comment by kannna5296** [comment]
DevOps側のServiceConnectionでなんとかなった。
https://docs.microsoft.com/ja-jp/azure/devops/pipelines/migrate/from-classic-pipelines?view=azure-devops

・クラシックパイプラインから作る
・ymlを出力する（environmentServiceNameができる）
・いいようにカスタマイズ

```
    - task: TerraformCLI@0
      displayName: terraform plan
      inputs:
        command: plan
        environmentServiceName: cbc87b8f-a27f-4dbf-8427-b64695c53f2e //これが大事
```
